version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 80:80
  mongo:
    image: mongo:latest
    volumes:
      - /home/eduar/mongodata:/data/db
    ports:
      - 27017:27017
