version: '3.9'

services:
  app:
    image: webdevops/php-apache:7.4
    volumes:
      - .:/app
    ports:
      - 80:80
  db:
    image: mongo:latest
    volumes:
      - /home/eduar/mongodata:/data/db
    ports:
      - 27017:27017
